vpc-name      = "Jenkins-vpc-demo"
igw-name      = "Jenkins-igw-demo"
subnet-name   = "Jenkins-subnet-demo"
rt-name       = "Jenkins-route-table-demo"
sg-name       = "Jenkins-sg-demo"
instance-name = "Jenkins-server-demo"
key-name      = "jenkins-key"
iam-role      = "Jenkins-iam-role-demo"