apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: zict
spec:
  storageClassName: gp2
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0a73652724ad255cf
    fsType: ext4

