apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: zict  
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
