# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-configmap
data:
  {{- range $key, $value := .Values.configmap.environment_variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}